apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multinic-agent
  namespace: multinic-system
  labels:
    app.kubernetes.io/name: multinic-agent
    app.kubernetes.io/component: daemonset
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: multinic-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: multinic-agent
      annotations:
        prometheus.io/scrape: "false"
    spec:
      serviceAccountName: multinic-agent
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      containers:
      - name: multinic-agent
        image: multinic-agent:latest
        imagePullPolicy: Never  # 로컬 이미지 사용
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
        env:
        # Downward API로 노드 이름 주입
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # ConfigMap에서 환경변수 주입
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: DB_USERNAME
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: DB_DATABASE
        - name: DB_CHARSET
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: DB_CHARSET
        - name: DB_PARSE_TIME
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: DB_PARSE_TIME
        - name: DB_LOC
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: DB_LOC
        # Secret에서 비밀번호 주입
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: multinic-agent-secret
              key: DB_PASSWORD
        # Agent 설정
        - name: AGENT_CHECK_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: AGENT_CHECK_INTERVAL
        - name: AGENT_RETRY_COUNT
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: AGENT_RETRY_COUNT
        - name: AGENT_RETRY_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: AGENT_RETRY_INTERVAL
        # Kubernetes 설정
        - name: K8S_LABEL_PREFIX
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: K8S_LABEL_PREFIX
        - name: K8S_ANNOTATION_PREFIX
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: K8S_ANNOTATION_PREFIX
        # Netplan 설정
        - name: NETPLAN_CONFIG_PATH
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: NETPLAN_CONFIG_PATH
        - name: NETPLAN_BACKUP_PATH
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: NETPLAN_BACKUP_PATH
        - name: NETPLAN_DRY_RUN
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: NETPLAN_DRY_RUN
        # 로깅 설정
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: LOG_LEVEL
        - name: LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: LOG_FORMAT
        - name: LOG_OUTPUT
          valueFrom:
            configMapKeyRef:
              name: multinic-agent-config
              key: LOG_OUTPUT
        volumeMounts:
        - name: netplan-config
          mountPath: /etc/netplan
        - name: netplan-backup
          mountPath: /var/backups/netplan
        - name: host-run
          mountPath: /run
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: netplan-config
        hostPath:
          path: /etc/netplan
          type: DirectoryOrCreate
      - name: netplan-backup
        hostPath:
          path: /var/backups/netplan
          type: DirectoryOrCreate
      - name: host-run
        hostPath:
          path: /run
          type: Directory 