apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: multinic-system
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: service
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app.kubernetes.io/name: mariadb
  type: ClusterIP 