---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multinic-agent
  namespace: multinic-system
  labels:
    app.kubernetes.io/name: multinic-agent
    app.kubernetes.io/component: serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multinic-agent
  labels:
    app.kubernetes.io/name: multinic-agent
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multinic-agent
  labels:
    app.kubernetes.io/name: multinic-agent
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multinic-agent
subjects:
- kind: ServiceAccount
  name: multinic-agent
  namespace: multinic-system 